package edu.upv.poo;

import java.awt.Color;
import java.util.ArrayList;

/**
 * Contiene la definición del JFrame de la caja de herramientas de dibujo.
 * @author luisroberto
 */
public class PaintToolboxFrame extends javax.swing.JFrame {

    private final ArrayList<ToolsListener> toolsListeners = 
            new ArrayList<>();
   
    private int actualSize = 5;
    
    /**
     * Creates new form PaintToolboxFrame
     */
    public PaintToolboxFrame() {
        initComponents();
    }
    
    public void addToolsListener(ToolsListener l) {
        if (l == null) return;
        toolsListeners.add(l);
    }
    
    public void removeToolsListener(ToolsListener l) {
        if (l == null) return;
        toolsListeners.remove(l);
    }
    
    private void notifyColorChanged(Color color, String colorName) {
        for (ToolsListener l : toolsListeners) {
            ColorChangedEvent evt = 
                    new ColorChangedEvent(this, color, colorName);
            l.colorChanged(evt);
        }
    }
    
    private void notifySizeChanged(int actualSize) {
        for (ToolsListener l : toolsListeners) {
            SizeChangedEvent e = new SizeChangedEvent(this, actualSize);
            l.sizeChanged(e);
        }
    }
    
    private void notifyToolChanged(String tool) {
        for (ToolsListener l : toolsListeners) {
            l.toolChanged(new ToolChangedEvent(this, tool));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnColorBack = new javax.swing.JButton();
        btnColorBlue = new javax.swing.JButton();
        btnColorRed = new javax.swing.JButton();
        btnReducirSize = new javax.swing.JButton();
        btnIncrementarSize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnToolPencil = new javax.swing.JButton();
        btnToolLine = new javax.swing.JButton();
        btnToolRectangle = new javax.swing.JButton();
        btnToolCircle = new javax.swing.JButton();
        btnColorPinck = new javax.swing.JButton();
        btnColorMaeneta = new javax.swing.JButton();
        btnColorCyan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnColorBack.setText("Black");
        btnColorBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorBackActionPerformed(evt);
            }
        });

        btnColorBlue.setText("Blue");
        btnColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorBlueActionPerformed(evt);
            }
        });

        btnColorRed.setText("Red");
        btnColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorRedActionPerformed(evt);
            }
        });

        btnReducirSize.setText("-");
        btnReducirSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReducirSizeActionPerformed(evt);
            }
        });

        btnIncrementarSize.setText("+");
        btnIncrementarSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrementarSizeActionPerformed(evt);
            }
        });

        jLabel1.setText("Tools:");

        btnToolPencil.setText("Pencil");
        btnToolPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolPencilActionPerformed(evt);
            }
        });

        btnToolLine.setText("Line");
        btnToolLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolLineActionPerformed(evt);
            }
        });

        btnToolRectangle.setText("Rectangle");
        btnToolRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolRectangleActionPerformed(evt);
            }
        });

        btnToolCircle.setText("Circle");
        btnToolCircle.setToolTipText("");
        btnToolCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolCircleActionPerformed(evt);
            }
        });

        btnColorPinck.setText("Pink");
        btnColorPinck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorPinckActionPerformed(evt);
            }
        });

        btnColorMaeneta.setText("Magenta");
        btnColorMaeneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorMaenetaActionPerformed(evt);
            }
        });

        btnColorCyan.setText("Cyan");
        btnColorCyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorCyanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColorMaeneta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorPinck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToolPencil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToolLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToolCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToolRectangle, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncrementarSize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReducirSize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnColorCyan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnColorBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorPinck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorMaeneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColorCyan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncrementarSize)
                    .addComponent(btnReducirSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolPencil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolRectangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolCircle)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorBackActionPerformed
        notifyColorChanged(Color.BLACK, "Black");
    }//GEN-LAST:event_btnColorBackActionPerformed

    private void btnColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorBlueActionPerformed
        notifyColorChanged(Color.BLUE, "Blue");
    }//GEN-LAST:event_btnColorBlueActionPerformed

    private void btnColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorRedActionPerformed
        notifyColorChanged(Color.RED, "Red");
    }//GEN-LAST:event_btnColorRedActionPerformed

    private void btnReducirSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReducirSizeActionPerformed
        if (actualSize == 1) return;
        actualSize--;
        notifySizeChanged(actualSize);
    }//GEN-LAST:event_btnReducirSizeActionPerformed

    private void btnIncrementarSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrementarSizeActionPerformed
        actualSize++;
        notifySizeChanged(actualSize);
    }//GEN-LAST:event_btnIncrementarSizeActionPerformed

    private void btnToolPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolPencilActionPerformed
        notifyToolChanged(Tool.PENCIL);
    }//GEN-LAST:event_btnToolPencilActionPerformed

    private void btnToolLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolLineActionPerformed
        notifyToolChanged(Tool.LINE);
    }//GEN-LAST:event_btnToolLineActionPerformed

    private void btnToolRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolRectangleActionPerformed
        notifyToolChanged(Tool.RECTANGLE);
    }//GEN-LAST:event_btnToolRectangleActionPerformed

    private void btnToolCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolCircleActionPerformed
        notifyToolChanged(Tool.CIRCLE);
    }//GEN-LAST:event_btnToolCircleActionPerformed

    private void btnColorPinckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorPinckActionPerformed
        notifyColorChanged(Color.PINK, "Pink");
    }//GEN-LAST:event_btnColorPinckActionPerformed

    private void btnColorMaenetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorMaenetaActionPerformed
        notifyColorChanged(Color.MAGENTA, "Magenta");
    }//GEN-LAST:event_btnColorMaenetaActionPerformed

    private void btnColorCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorCyanActionPerformed
       notifyColorChanged(Color.CYAN, "Cyan");
    }//GEN-LAST:event_btnColorCyanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorBack;
    private javax.swing.JButton btnColorBlue;
    private javax.swing.JButton btnColorCyan;
    private javax.swing.JButton btnColorMaeneta;
    private javax.swing.JButton btnColorPinck;
    private javax.swing.JButton btnColorRed;
    private javax.swing.JButton btnIncrementarSize;
    private javax.swing.JButton btnReducirSize;
    private javax.swing.JButton btnToolCircle;
    private javax.swing.JButton btnToolLine;
    private javax.swing.JButton btnToolPencil;
    private javax.swing.JButton btnToolRectangle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
