package edu.upv.poo;

import java.security.SecureRandom;
import java.util.ArrayList;

/**
 * 
 * @author luisroberto
 */
public class SubjectFrame extends javax.swing.JFrame {

    private ArrayList<ReceptorListener> receptores = new ArrayList<>();
    
    /**
     * Creates new form SubjectFrame
     */
    public SubjectFrame() {
        initComponents();
    }
    
    public void addReceptorListener(ReceptorListener l) {
        if (l == null) return;
        receptores.add(l);
    }
    
    public void removeReceptorListener(ReceptorListener l) {
        if (l == null) return;
        receptores.remove(l);
    }
    
    private void notificar(String algunDato) {
        System.out.println("Cantidad de Receptores: " + receptores.size());
        for (ReceptorListener l : receptores) {
            l.notificacionRecibida(new NotificacionEvent(this, algunDato));
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNotificar = new javax.swing.JButton();

        setTitle("Subject");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnNotificar.setText("Notificar");
        btnNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNotificar, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarActionPerformed
        String dato = "" +  new SecureRandom().nextLong();
        notificar(dato);
    }//GEN-LAST:event_btnNotificarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Closed!!!");
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificar;
    // End of variables declaration//GEN-END:variables
}
